server:
  port: 8082
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: empleado-service
          uri: lb://empleado-service
          predicates:
            - Path=/empleado/**
        - id: marca-tiempo-service
          uri: lb://marca-tiempo-service
          predicates:
            - Path=/marca-tiempo/**
        - id: justificativo-inasistencia-service
          uri: lb://justificativo-inasistencia-service
          predicates:
            - Path=/justificativo-inasistencia/**
        - id: justificativo-hora-extra-service
          uri: lb://justificativo-hora-extra-service
          predicates:
            - Path=/justificativo-hora-extra/**
        - id: planilla-service
          uri: lb://planilla-service
          predicates:
            - Path=/planilla/**